image: gitpod/workspace-full-vnc

# Commands that will run on workspace start
tasks:
    - name: Server
      before: sudo apt-get update && pyenv install 3.10.12 && pyenv local 3.10.12 && sudo apt install tesseract-ocr -y
      init: pip install -r server/requirements.txt
      command: python server/manage.py runserver 

    - name: Frontend
      before: cd app
      init: npm install
      command: npm run dev

# Ports to expose on workspace startup
ports:
    - port: 8000
      name: Server
      description: Server Preview
      visibility: public
      protocol: http
    
    - port: 5713
      onOpen: open-preview
      name: Server
      description: Server Preview
      visibility: public
      protocol: http
